globalThis.ADMIN_ATLAS_CATALOG = [
  {category:"Overview",method:"GET",path:"/info",summary:"Server, API and current user information.",privilege:"Any %Admin privilege",risk:"read"},
  {category:"System",method:"GET",path:"/v2/monitor/dashboard/system-resources",summary:"Dashboard statistics for system resources.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"System",method:"GET",path:"/v2/monitor/system-usage",summary:"System usage statistics.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"System",method:"GET",path:"/v2/monitor/system-usage/shared-memory",summary:"Shared-memory usage statistics.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"System",method:"GET",path:"/v2/processes",summary:"List running IRIS processes.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"System",method:"GET",path:"/v2/process",summary:"Inspect one IRIS process.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"System",method:"POST",path:"/v2/process/suspend",summary:"Suspend an IRIS process.",privilege:"%Admin_Operate:U",risk:"write"},
  {category:"System",method:"POST",path:"/v2/process/resume",summary:"Resume an IRIS process.",privilege:"%Admin_Operate:U",risk:"write"},
  {category:"System",method:"POST",path:"/v2/process/terminate",summary:"Terminate an IRIS process.",privilege:"%Admin_Operate:U",risk:"danger"},
  {category:"Web apps",method:"GET",path:"/v2/web-apps",summary:"List web applications.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Web apps",method:"GET",path:"/v2/web-app",summary:"Inspect a web application.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Web apps",method:"PUT",path:"/v2/web-app",summary:"Create or edit a web application.",privilege:"%Admin_Secure:U",risk:"write"},
  {category:"Web apps",method:"DELETE",path:"/v2/web-app",summary:"Delete a web application.",privilege:"%Admin_Secure:U",risk:"danger"},
  {category:"Permissions",method:"GET",path:"/v2/security/users",summary:"List users.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Permissions",method:"GET",path:"/v2/security/roles",summary:"List roles.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Permissions",method:"GET",path:"/v2/security/resources",summary:"List security resources.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Permissions",method:"GET",path:"/v2/security/role/owners",summary:"List users and owners that hold a role.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Permissions",method:"GET",path:"/v2/security/sql-privileges",summary:"Inspect SQL privileges for a grantee.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Security",method:"GET",path:"/v2/security/audit/enabled",summary:"Check whether auditing is enabled.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Security",method:"GET",path:"/v2/security/audit/events",summary:"List audit event definitions.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Security",method:"POST",path:"/v2/security/audit/records",summary:"Search audit records.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Security",method:"GET",path:"/v2/security/oauth2/resource-servers",summary:"List OAuth2 resource servers.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Security",method:"GET",path:"/v2/security/oauth2/client/server-definitions",summary:"List configured OAuth2 authorization servers.",privilege:"%Admin_OAuth2_Client:U",risk:"read"},
  {category:"Tasks",method:"GET",path:"/v2/tasks",summary:"List scheduled tasks.",privilege:"%Admin_Operate:U or %Admin_Task:U",risk:"read"},
  {category:"Tasks",method:"GET",path:"/v2/task/upcoming",summary:"List upcoming task executions.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"Tasks",method:"GET",path:"/v2/task/history",summary:"View task execution history.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"Tasks",method:"GET",path:"/v2/async-results",summary:"View asynchronous administration jobs.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"Tasks",method:"POST",path:"/v2/async-result/pause",summary:"Pause an asynchronous administration job.",privilege:"%Admin_Operate:U",risk:"write"},
  {category:"Tasks",method:"POST",path:"/v2/async-result/resume",summary:"Resume an asynchronous administration job.",privilege:"%Admin_Operate:U",risk:"write"},
  {category:"Tasks",method:"POST",path:"/v2/async-result/cancel",summary:"Cancel an asynchronous administration job.",privilege:"%Admin_Operate:U",risk:"danger"},
  {category:"Logs",method:"GET",path:"/v2/security/audit/record",summary:"Inspect one audit record.",privilege:"%Admin_Secure:U",risk:"read"},
  {category:"Logs",method:"POST",path:"/v2/journal/file/records",summary:"List records from an IRIS journal file.",privilege:"%Admin_Operate:U",risk:"read"},
  {category:"Storage",method:"GET",path:"/v2/devices",summary:"List configured devices.",privilege:"%Admin_Manage:U",risk:"read"},
  {category:"Storage",method:"GET",path:"/v2/device/settings",summary:"Inspect telnet and device I/O settings.",privilege:"%Admin_Manage:U",risk:"read"}
];